spring.application.name=hello-world
coach.name=Mickey
team.name=The mouse crew
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=hello app
info.app.description=practicing in bangalore
info.app.version=1.0.0

info.nope.name=hello app
info.nope.description=practicing in bangalore
info.nope.version=1.0.0

spring.security.user.name=sreenivas
spring.security.user.password=123456
spring.main.lazy_initialization=true